version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: news-backend-postgres
    env_file: 
      - ./compose.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - news-backend-network

volumes:
  postgres_data:

networks:
  news-backend-network:
    driver: bridge
