# Generated by Django 5.1.1 on 2024-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image_link",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="news",
            name="original_link",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.TextField(),
        ),
    ]
