# Generated by Django 5.1.1 on 2024-09-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_image_link_alter_news_original_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="original_link",
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
